import {API_BASE_URL,setApiBase} from './config.js';
const $=id=>document.getElementById(id); let file=null; let busy=false;
const base=()=>((localStorage.getItem('typo_api_base')||API_BASE_URL||'').replace(/\/$/,''));
const fmtBytes=n=>{if(!n)return '0 B';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return `${x.toFixed(i?1:0)} ${u[i]}`};
function setStatus(s){$('status').textContent=s} function setProgress(v,text){v=Math.max(0,Math.min(100,v));$('progressBar').style.width=v+'%';$('progressPercent').textContent=Math.round(v)+'%';if(text)$('progressText').textContent=text}
function setEngine(kind,text){const e=$('engineState');e.className='pill '+kind;e.innerHTML='<i></i>'+text}
function resetStats(){['pages','ocrPages','words','tables'].forEach(id=>$(id).textContent='0');$('confidence').textContent='—';$('processingTime').textContent='—';$('structure').innerHTML='<div class="empty-state">هنوز تحلیلی انجام نشده است.</div>'}
function setFile(f){if(!f)return;const ok=['application/pdf','image/png','image/jpeg'].includes(f.type)||/\.(pdf|png|jpe?g)$/i.test(f.name);if(!ok){setStatus('فرمت پشتیبانی نمی‌شود. فقط PDF، PNG و JPG/JPEG مجاز است.');return}if(f.size>75*1024*1024){setStatus('حجم فایل بیش از 75 MB است.');return}file=f;$('fileName').textContent=f.name;$('fileMeta').hidden=false;$('fileType').textContent=(f.type||'FILE').toUpperCase();$('fileSize').textContent=fmtBytes(f.size);$('convertBtn').disabled=false;resetStats();setProgress(0,'فایل آماده');setStatus('فایل آماده پردازش است.');}
$('fileInput').addEventListener('change',e=>setFile(e.target.files[0]));
$('dropZone').addEventListener('dragover',e=>{e.preventDefault();$('dropZone').classList.add('drag')});$('dropZone').addEventListener('dragleave',()=>$('dropZone').classList.remove('drag'));$('dropZone').addEventListener('drop',e=>{e.preventDefault();$('dropZone').classList.remove('drag');setFile(e.dataTransfer.files[0])});$('dropZone').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('fileInput').click()}});
$('removeFile').addEventListener('click',()=>{file=null;$('fileInput').value='';$('fileMeta').hidden=true;$('fileName').textContent='PDF، PNG، JPG / JPEG';$('convertBtn').disabled=true;resetStats();setProgress(0,'آماده');setStatus('یک فایل انتخاب کنید.')});
async function checkServer(){try{const r=await fetch(base()+'/api/health',{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();$('serverStatus').textContent=`✓ آنلاین — ${j.version} — OCR: ${j.ocr}`;$('maxUpload').textContent=(j.max_upload_mb||75)+' MB';setEngine('online','آنلاین');return true}catch(e){$('serverStatus').textContent='⚠ Backend متصل نیست';setEngine('error','بدون سرور');return false}}
function showStats(headers,elapsed){$('pages').textContent=headers.get('X-TYPO-Pages')||'—';$('ocrPages').textContent=headers.get('X-TYPO-OCR-Pages')||'—';$('words').textContent=headers.get('X-TYPO-Words')||'—';$('tables').textContent=headers.get('X-TYPO-Tables')||'—';const c=headers.get('X-TYPO-Confidence');$('confidence').textContent=c?c+'%':'—';$('processingTime').textContent=(elapsed/1000).toFixed(1)+' ثانیه';const pages=+$('pages').textContent||0,ocr=+$('ocrPages').textContent||0,tables=+$('tables').textContent||0,words=+$('words').textContent||0;$('structure').innerHTML=`<div class="structure-grid"><div class="structure-card"><b>${pages}</b><span>صفحه پردازش‌شده</span></div><div class="structure-card"><b>${ocr}</b><span>صفحه با OCR</span></div><div class="structure-card"><b>${words.toLocaleString('fa-IR')}</b><span>کلمه/توکن استخراج‌شده</span></div><div class="structure-card"><b>${tables}</b><span>جدول بازسازی‌شده</span></div><div class="structure-card"><b>${c?c+'%':'—'}</b><span>میانگین اعتماد OCR</span></div><div class="structure-card"><b>${elapsed<60000?(elapsed/1000).toFixed(1)+'s':Math.round(elapsed/60000)+'m'}</b><span>زمان پردازش</span></div></div>`}
async function convert(){if(!file||busy)return;busy=true;$('convertBtn').disabled=true;$('progress').classList.add('active');setEngine('','در حال پردازش');setProgress(5,'در حال آماده‌سازی فایل');setStatus('فایل در حال ارسال به موتور سرور است…');const ok=await checkServer();if(!ok){setStatus('Backend در دسترس نیست. ابتدا Docker/سرور را اجرا کنید.');busy=false;$('convertBtn').disabled=false;$('progress').classList.remove('active');setProgress(0,'آماده');return}const fd=new FormData();fd.append('file',file,file.name);const q=new URLSearchParams({ocr_mode:$('ocrMode').value,language:$('ocrLang').value,table_mode:$('tableMode').value,ocr_quality:$('ocrQuality').value,preserve_style:$('preserveStyle').checked?'true':'false',smart_paragraphs:$('smartParagraphs').checked?'true':'false',safe_tables:$('safeTables').checked?'true':'false'});const started=performance.now();try{setProgress(18,'استخراج ساختار PDF / تصویر');setStatus('استخراج متن مستقیم و بررسی کیفیت صفحات…');const r=await fetch(base()+'/api/convert?'+q,{method:'POST',body:fd});if(!r.ok){let msg='خطای سرور';try{const j=await r.json();msg=j.detail||msg}catch{}throw new Error(msg)}setProgress(78,'بازسازی DOCX و جدول‌ها');const blob=await r.blob();setProgress(94,'آماده‌سازی فایل خروجی');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name.replace(/\.[^.]+$/,'')+'-TYPO-Real.docx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);const elapsed=performance.now()-started;showStats(r.headers,elapsed);setProgress(100,'تکمیل شد');setStatus('✓ تبدیل واقعی انجام شد. فایل DOCX دانلود شد.');setEngine('online','آنلاین')}catch(e){console.error(e);setProgress(0,'خطا');setStatus('خطا: '+(e.message||e));setEngine('error','خطا')}finally{busy=false;$('convertBtn').disabled=!file;$('progress').classList.remove('active')}}
$('convertBtn').addEventListener('click',convert);
$('settingsBtn').addEventListener('click',()=>{const d=$('settingsDialog');$('apiBaseInput').value=localStorage.getItem('typo_api_base')||'';d.showModal()});$('saveSettings').addEventListener('click',()=>{setApiBase($('apiBaseInput').value.trim());setTimeout(checkServer,0)});
checkServer();
